### ISSUE TITLE
Add new elements

### ISSUE THREAD

**Issue by selimaj-dev** [orus-dev/osui#6]
The following elements:
- Input
- File chooser
- Outline css

**Comment by FizzWizZleDazzle** [comment]
So is this an issue or what?

**Comment by selimaj-dev** [comment]
> So is this an issue or what?
> 
> 

Yes it is indeed an issue.. Why?

**Comment by FizzWizZleDazzle** [comment]
The context I have is "Add new elements" and "Input, File chooser, Outline css." So is this broken or doesn't exist.

**Comment by selimaj-dev** [comment]
> The context I have is "Add new elements" and "Input, File chooser, Outline css." So is this broken or doesn't exist.

Oh ok. To awnser you question. This issue is for new elements to be added. In the current state

- Outline css: Needs fixing by refractoring the rendering system aka 'Writer' and 'Frame'.

- Input: i added it (takes user input)

- File chooser: not yet added, but can be made using the current existing elements.

**Comment by FizzWizZleDazzle** [comment]
Ok, need help on file chooser?

**Comment by selimaj-dev** [comment]
> Ok, need help on file chooser?

Sure, but it’s not really my top priority right now because of the outline issue though.
